In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,454544],np.int8)
print(arr) #size is 8 byte,so memory effiecient
print(arr.dtype)

[   1    2    3    4    5    6 -112]
int8


In [3]:
#create array by defining dimension and type
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)
a = np.array([1, 2, 3], dtype = complex)
print(a)

[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]


# Sahpe & size

In [4]:
arr=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.size)
arr=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]],np.int16) #size if 16 bits
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.size)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
(2, 6)
int32
12
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
(2, 6)
int16
12


In [5]:
arr.itemsize*arr.size #itemsize ->size of item  size-> size of array

24

# Array Creation

In [6]:
print(np.zeros((2,5))) #2*5 arrey with value 0
print(np.ones(5)) #1d array if size 5 with value 1
print(np.ones([3,3])) #3*3 array with value 1

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
np.arange(15) #1D array from 0-14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.linspace(1,5,12) #12 equally divided element b/w 1 to 5

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [9]:
np.empty((4,6)) #createsize of  4,6 array with random number

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34608432e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.24611674e-306, 1.29061821e-306,
        6.23057349e-307, 2.22522597e-306, 1.06810268e-306],
       [6.23052935e-307, 1.33511562e-306, 6.89805151e-307,
        2.22522597e-306, 1.33511969e-306, 8.34426039e-308]])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Reshaping Array

In [11]:
arr=np.arange(15)
print(arr)
arr=arr.reshape(3,5) #shape array in 3 part
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
arr=arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# use of axis

In [13]:
arr=np.array([[1,2,3],[4,5,6],[7,1,0]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [14]:
arr.sum(axis=0) #vertically

array([12,  8,  9])

In [15]:
arr.sum(axis=1) #axis=1 horizontally

array([ 6, 15,  8])

In [16]:
arr.T #transpose of matrix

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

# Slicing

In [17]:
arr=np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
print(arr[0:8])
print(arr[8:])
print(arr[-9:-1])

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15 16 17 18 19]
[11 12 13 14 15 16 17 18]


# sort numpy array

In [19]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
arr = np.array([True, False, True])
print(np.sort(arr))
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
[False  True  True]
[[2 3 4]
 [0 1 5]]


# Arithmetic Operation

In [20]:
arr1=np.array([[1,2,3],[4,5,6],[7,1,0]])
arr2=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [21]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [22]:
arr2*arr1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [23]:
np.sqrt(arr1) #square root of each element

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [24]:
arr1.sum()

29

In [25]:
arr1.min()

0

In [26]:
arr1.max()

7

In [27]:
np.count_nonzero(arr1)

8

In [28]:
np.nonzero(arr) #tuple of ([row],[column])

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 2], dtype=int64))

# Where in numpy

In [29]:
arr1 = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr1 == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [30]:
np.where(arr1>3)

(array([3, 4, 5, 6], dtype=int64),)

In [31]:
arr=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [32]:
np.where(arr>4) #tuple of ([row],[column])

(array([1, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))

# Concatenate and array_split

In [33]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.concatenate((arr1, arr2)))
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[1 2 3 4 5 6 7 8]
[[1 2 5 6]
 [3 4 7 8]]


In [34]:
#array_split in 2D array
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print(newarr)
newarr = np.array_split(arr, 4)
print(newarr)
newarr = np.array_split(arr, 5)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


# Sorting numpy array

In [35]:
#sort array
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
arr = np.array([True, False, True])
print(np.sort(arr))
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
[False  True  True]
[[2 3 4]
 [0 1 5]]


# Stacking an Array 

In [36]:
#stack along ROW
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
print( np.hstack((arr, arr1)))

[1 2 3 4 5 6]
[1 2 3 4 5 6 1 2 3]


In [37]:
#stack along COLUMN
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [38]:
#stack along hegiht
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
